# Main Navigation Menu
[[main]]
name = "Home"
pageRef = "/"
identifier = "home"
weight = 10

[[main]]
name = "Blog"
pageRef = "Blog"
identifier = "blog"
weight = 20

[[main]]
name = "Toolkit"
pageRef = "Toolkit"
identifier = "toolkit"
weight = 30

# About Section with Submenus
[[main]]
name = "About"
identifier = "about"
weight = 40

[[main]]
name = "About Me"
pageRef = "Aboutme"
parent = "about"
identifier = "about-me"
weight = 41

[[main]]
name = "Interests"
pageRef = "interests"
parent = "about"
identifier = "Interests"
weight = 42

# Social Media Links
[[main]]
pre = "github"
url = "https://github.com/SalahThabet1"
identifier = "github"
weight = 100

[[main]]
pre = "instagram"
url = "https://www.instagram.com/salah.thabet/"
identifier = "instagram"
weight = 101

[[main]]
pre = "youtube"
url = "https://www.youtube.com/@salahdinthabet5684"
identifier = "youtube"
weight = 102

# Footer Menu
[[footer]]
none = "none"
